### ISSUE TITLE
torch is required for pre-compiling ops, please install it first.

### ISSUE THREAD

**Issue by kadirnar** [Megvii-BaseDetection/YOLOX#1368]
Hi @FateScript,

The torch library needs to be loaded before running this command.
Install Code:
```
pip install -v -e .
```
Error Message:
```
assert TORCH_AVAILABLE, "torch is required for pre-compiling ops, please install it first."
AssertionError: torch is required for pre-compiling ops, please install it first.
[WARNING] Unable to import torch, pre-compiling ops will be disabled.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
GPU:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
```
CPU:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
```

**Comment by FateScript** [comment]
@kadirnar  Yes, torch is required before install yolox. Fix this later.

**Comment by nickovaras** [comment]
This still happens.

**Comment by nickovaras** [comment]
Skipping 
`pip3 install -U pip`
Did the trick for me

**Comment by junwenwu** [comment]
Looks like torch2 is not supported. I rolled back to torch1.13.1 and installed without any problem.

**Comment by moonlight888666** [comment]
@kadirnar I also encountered the same problem as you. I already have torch in my environment, but why is it still unable to import torch? This problem has not been solved for a long time

**Comment by Nao-Y1996** [comment]
@moonlight888666 
In my case, this issue was caused by the version of setuptools. 
The error occurred with setuptools-70.0, but it did not occur with setuptools-65.5.

However, my project includes YOLOX as a git submodule and has many other dependencies, so there may be other underlying issues.

**Comment by pskopnik** [comment]
I installed YOLOX into a fresh venv on Python 3.12 (pip 24.1.2, setuptools 70.3.0) with Pytorch 2.3.1:

Nowadays, pip builds a package in an isolated environment before installing them into the (virtual) environment.
Projects are supposed to declare their build dependencies in a `pyproject.tml`, see [PEP 517 and related](https://peps.python.org/pep-0517/).
This is not yet implemented for this repo.

 1. `pip3 install -U pip setuptools` to make sure the latest `setuptools` package is available for importing
 1. Pre-install [PyTorch](https://pytorch.org/get-started/locally/), e.g. `pip3 install torch torchvision torchaudio`
 1. I also stumbled across https://github.com/daquexian/onnx-simplifier/issues/286
    * In `requirements.txt`, replace `onnx-simplifier==0.4.10` by `onnxsim==0.4.13`

Finally:

```shell
pip install --no-build-isolation -v -e .
```

Downgrading to setuptools < 66 also works, because it does not yet perform build isolation by default.
