### ISSUE TITLE
关于模型压缩

### ISSUE THREAD

**Issue by 15162162323** [Megvii-BaseDetection/YOLOX#507]
对于yolox模型，有没有剪枝、量化的实践呢？

**Comment by Joker316701882** [comment]
@15162162323 Currently not supported. But YOLOX is not different. You can try almost all pruning and quantization method on YOLOX as long as they work well on other YOLO series.

**Comment by Sanster** [comment]
I implemented [Learning Efficient Convolutional Networks Through Network Slimming](http://openaccess.thecvf.com/content_iccv_2017/html/Liu_Learning_Efficient_Convolutional_ICCV_2017_paper.html) on YOLOX: [YOLOX-Slim](https://github.com/Sanster/YOLOX-Slim)

Some result:

Using YOLOX-s model for sparse training, pruning and then fine-tuning, I expected to be able to train a slimming model with better mAP and smaller parameters than YOLOX-Tiny. However, due to limited GPU resources, both models were not fully trained (120 and 25 rounds), and the training hyper parameters and strategies are yet to be explored.


| Model | size | mAP<sup>val<br>0.5:0.95 |  Params<br>(M) | FLOPs<br>(G) | weights | notes |
|-------|------|-------------------------|----------------|--------------|---------|-------|
|YOLOX-s(sparse-training) |640  | 37.9 | 9.0 | 26.8 | [github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_sparsity_train/latest_ckpt.pth) | max_epoch 120, linear warm up to `s=0.0001`|
|YOLOX-s(slimming model) |640  |16.5  | 1.58  | 6.43 | [github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.pth) [github-onnx](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.onnx)| network_slim_ratio=0.65, max_epoch=25 |
|YOLOX-s(Official)    |640  |40.5 | 9.0 | 26.8 | [github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth) |
|YOLOX-Tiny(Official) |416  |32.8 | 5.06 | 6.45 | [github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth) |

**Comment by vaerdu** [comment]
> I implemented [Learning Efficient Convolutional Networks Through Network Slimming](http://openaccess.thecvf.com/content_iccv_2017/html/Liu_Learning_Efficient_Convolutional_ICCV_2017_paper.html) on YOLOX: [YOLOX-Slim](https://github.com/Sanster/YOLOX-Slim)
> 
> Some result:
> 
> Using YOLOX-s model for sparse training, pruning and then fine-tuning, I expected to be able to train a slimming model with better mAP and smaller parameters than YOLOX-Tiny. However, due to limited GPU resources, both models were not fully trained (120 and 25 rounds), and the training hyper parameters and strategies are yet to be explored.
> 
> Model	size	mAPval
> 0.5:0.95	Params
> (M)	FLOPs
> (G)	weights	notes
> YOLOX-s(sparse-training)	640	37.9	9.0	26.8	[github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_sparsity_train/latest_ckpt.pth)	max_epoch 120, linear warm up to `s=0.0001`
> YOLOX-s(slimming model)	640	16.5	1.58	6.43	[github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.pth) [github-onnx](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.onnx)	network_slim_ratio=0.65, max_epoch=25
> YOLOX-s(Official)	640	40.5	9.0	26.8	[github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth)	
> YOLOX-Tiny(Official)	416	32.8	5.06	6.45	[github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth)

您好，可以请教您一下如何对YOLOX-s模型进行剪枝吗？

**Comment by lizexu123** [comment]
> I implemented [Learning Efficient Convolutional Networks Through Network Slimming](http://openaccess.thecvf.com/content_iccv_2017/html/Liu_Learning_Efficient_Convolutional_ICCV_2017_paper.html) on YOLOX: [YOLOX-Slim](https://github.com/Sanster/YOLOX-Slim)
> 
> Some result:
> 
> Using YOLOX-s model for sparse training, pruning and then fine-tuning, I expected to be able to train a slimming model with better mAP and smaller parameters than YOLOX-Tiny. However, due to limited GPU resources, both models were not fully trained (120 and 25 rounds), and the training hyper parameters and strategies are yet to be explored.
> 
> Model	size	mAPval
> 0.5:0.95	Params
> (M)	FLOPs
> (G)	weights	notes
> YOLOX-s(sparse-training)	640	37.9	9.0	26.8	[github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_sparsity_train/latest_ckpt.pth)	max_epoch 120, linear warm up to `s=0.0001`
> YOLOX-s(slimming model)	640	16.5	1.58	6.43	[github](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.pth) [github-onnx](https://github.com/Sanster/models/raw/master/YOLOX/yolox_s_slim_fine_tuning/latest_ckpt.onnx)	network_slim_ratio=0.65, max_epoch=25
> YOLOX-s(Official)	640	40.5	9.0	26.8	[github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth)	
> YOLOX-Tiny(Official)	416	32.8	5.06	6.45	[github](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth)


您好，能借鉴一下源码吗，学习一下，我自己写了一部分，但是不对
Hello, can you use the source code for reference? I wrote a part myself, but it's wrong
