### ISSUE TITLE
CUDA out of memory error.

### ISSUE THREAD

**Issue by Atmika293** [Megvii-BaseDetection/YOLOX#608]
I am trying to train yolox_s on a custom dataset. Each image is a .jpg file of size 1280x720, which gets resized to 640x640.
I converted the annotations from the original YOLOv5 format to COCO format using the YOLO2COCO repository linked in README.

This is my experiment file:

```
import os

import torch
import torch.distributed as dist

from yolox.data import get_yolox_datadir
from yolox.exp import Exp as MyExp


class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.depth = 0.33
        self.width = 0.50
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]

        # Define yourself dataset path
        self.data_dir = "datasets/helmets"
        self.train_ann = "instances_train2017.json"
        self.val_ann = "instances_val2017.json"

        self.num_classes = 1

        self.max_epoch = 300
        self.data_num_workers = 4
        self.eval_interval = 1
```
When I run 
`python tools/train.py -f exps/example/custom/helmet_detection.py -d 1 -b 16 --fp16 -o -c yolox_s.pth`

I get the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 4.51 GiB (GPU 0; 6.00 GiB total capacity; 110.28 MiB already allocated; 4.44 GiB free; 120.00 MiB reserved in total by PyTorch)`

I have tried reducing the batch size, and even resizing the images in the dataset to 640x640, but I keep getting the same error with almost the same allocation size everytime. I don't understand where 4.51 GiB allocation is coming from. Any insight is appreciated.

Thanks in advance!

**Comment by Joker316701882** [comment]
Does -b 8 help?



发自我的iPhone


------------------ Original ------------------
From: Atmika293 ***@***.***&gt;
Date: Sat,Aug 28,2021 11:47 AM
To: Megvii-BaseDetection/YOLOX ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Megvii-BaseDetection/YOLOX] CUDA out of memory error. (#608)





 
I am trying to train yolox_s on a custom dataset. Each image is a .jpg file of size 1280x720, which gets resized to 640x640.
 I converted the annotations from the original YOLOv5 format to COCO format using the YOLO2COCO repository linked in README.
 
This is my experiment file:
 import os import torch import torch.distributed as dist from yolox.data import get_yolox_datadir from yolox.exp import Exp as MyExp class Exp(MyExp):     def __init__(self):         super(Exp, self).__init__()         self.depth = 0.33         self.width = 0.50         self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]         # Define yourself dataset path         self.data_dir = "datasets/helmets"         self.train_ann = "instances_train2017.json"         self.val_ann = "instances_val2017.json"         self.num_classes = 1         self.max_epoch = 300         self.data_num_workers = 4         self.eval_interval = 1  
When I run
 python tools/train.py -f exps/example/custom/helmet_detection.py -d 1 -b 16 --fp16 -o -c yolox_s.pth
 
I get the following error:
 RuntimeError: CUDA out of memory. Tried to allocate 4.51 GiB (GPU 0; 6.00 GiB total capacity; 110.28 MiB already allocated; 4.44 GiB free; 120.00 MiB reserved in total by PyTorch)
 
I have tried reducing the batch size, and even resizing the images in the dataset to 640x640, but I keep getting the same error with almost the same allocation size everytime. I don't understand where 4.51 GiB allocation is coming from. Any insight is appreciated.
 
Thanks in advance!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Atmika293** [comment]
> 
> Does -b 8 help? 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Atmika293 ***@***.***&gt; Date: Sat,Aug 28,2021 11:47 AM To: Megvii-BaseDetection/YOLOX ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [Megvii-BaseDetection/YOLOX] CUDA out of memory error. (#608) I am trying to train yolox_s on a custom dataset. Each image is a .jpg file of size 1280x720, which gets resized to 640x640. I converted the annotations from the original YOLOv5 format to COCO format using the YOLO2COCO repository linked in README. This is my experiment file: import os import torch import torch.distributed as dist from yolox.data import get_yolox_datadir from yolox.exp import Exp as MyExp class Exp(MyExp): def __init__(self): super(Exp, self).__init__() self.depth = 0.33 self.width = 0.50 self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0] # Define yourself dataset path self.data_dir = "datasets/helmets" self.train_ann = "instances_train2017.json" self.val_ann = "instances_val2017.json" self.num_classes = 1 self.max_epoch = 300 self.data_num_workers = 4 self.eval_interval = 1 When I run python tools/train.py -f exps/example/custom/helmet_detection.py -d 1 -b 16 --fp16 -o -c yolox_s.pth I get the following error: RuntimeError: CUDA out of memory. Tried to allocate 4.51 GiB (GPU 0; 6.00 GiB total capacity; 110.28 MiB already allocated; 4.44 GiB free; 120.00 MiB reserved in total by PyTorch) I have tried reducing the batch size, and even resizing the images in the dataset to 640x640, but I keep getting the same error with almost the same allocation size everytime. I don't understand where 4.51 GiB allocation is coming from. Any insight is appreciated. Thanks in advance! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Atmika293** [comment]
No, -b 8 gives me the same error.

**Comment by allenchertk** [comment]
Does  python tools/train.py -f exps/example/custom/helmet_detection.py -d 1 -b 2 -c yolox_s.pth  help?

**Comment by Atmika293** [comment]
I finally managed to solve the issue. I switched to a Linux machine with 8 GiB capacity. The same command works on that machine. I think the problem may have been with the GPU itself.
