### ISSUE TITLE
我安装YOLOX出现了这样的问题，是什么原因呢？

### ISSUE THREAD

**Issue by lihui669** [Megvii-BaseDetection/YOLOX#86]
WARNING: Discarding file:///D:/LH/code/YOLOX-main. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
![image](https://user-images.githubusercontent.com/40649829/126647961-3dddff85-552e-44b8-ab84-86441d929589.png)

**Comment by captainfffsama** [comment]
pytorch vision must >=1.3

**Comment by lihui669** [comment]
> pytorch vision must >=1.3
您好，我把pytorch换成1.6   依然报相同的错误
![image](https://user-images.githubusercontent.com/40649829/126650740-7897b3c4-7c39-4c7f-8ecb-afcd00765926.png)

**Comment by myrzx** [comment]
我把setup.py里读取readme.md的部分注释掉，然后成功安装YOLOX

**Comment by TianQingX** [comment]
> 我把setup.py里读取readme.md的部分注释掉，然后成功安装YOLOX

会报另外一个错误。

ERROR: Command errored out with exit status 1: 'C:\Users\10653\.conda\envs\yolox\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Detection\\YOLOX-main\\setup.py'"'"'; __file__='"'"'D:\\Detection\\YOLOX-main\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by TianQingX** [comment]
![image](https://user-images.githubusercontent.com/40229906/126724267-4c2ed227-5498-4eae-94ef-d678307bb46d.png)
![image](https://user-images.githubusercontent.com/40229906/126724288-e0fd5e22-2542-42c4-8b95-9f3a3511489b.png)

不知道是不是torch原因不匹配，还是没有装C++的原因？
https://zhuanlan.zhihu.com/p/89858202

(yolox) D:\Detection\YOLOX-main\apex>pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"--use-feature=in-tree-build ./
C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\commands\install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.1.3 from C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\10653\AppData\Local\Temp\pip-ephem-wheel-cache-ab40__rq
Created temporary directory: C:\Users\10653\AppData\Local\Temp\pip-req-tracker-ca4m71x7
Initialized build tracking at C:\Users\10653\AppData\Local\Temp\pip-req-tracker-ca4m71x7
Created build tracker: C:\Users\10653\AppData\Local\Temp\pip-req-tracker-ca4m71x7
Entered build tracker: C:\Users\10653\AppData\Local\Temp\pip-req-tracker-ca4m71x7
Created temporary directory: C:\Users\10653\AppData\Local\Temp\pip-install-ed4yzzl9
Processing d:\detection\yolox-main\apex
  Created temporary directory: C:\Users\10653\AppData\Local\Temp\pip-req-build-bxexyfxe
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Added file:///D:/Detection/YOLOX-main/apex to build tracker 'C:\\Users\\10653\\AppData\\Local\\Temp\\pip-req-tracker-ca4m71x7'
    Running setup.py (path:C:\Users\10653\AppData\Local\Temp\pip-req-build-bxexyfxe\setup.py) egg_info for package from file:///D:/Detection/YOLOX-main/apex
    Created temporary directory: C:\Users\10653\AppData\Local\Temp\pip-pip-egg-info-x8w0ngoc
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\10653\AppData\Local\Temp\pip-req-build-bxexyfxe\setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "C:\Users\10653\AppData\Local\Temp\pip-req-build-bxexyfxe\setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

WARNING: Discarding file:///D:/Detection/YOLOX-main/apex. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\commands\install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 104, in resolve
    req, requested_extras=()
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 444, in make_requirement_from_install_req
    raise self._build_failures[ireq.link]
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 312, in __init__
    version=version,
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\operations\prepare.py", line 571, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\operations\prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\distributions\sdist.py", line 36, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\req\req_install.py", line 549, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\req\req_install.py", line 529, in _generate_metadata
    details=self.name or f"from {self.link}"
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\operations\build\metadata_legacy.py", line 70, in generate_metadata
    command_desc='python setup.py egg_info',
  File "C:\Users\10653\.conda\envs\yolox\lib\site-packages\pip\_internal\utils\subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///D:/Detection/YOLOX-main/apex from build tracker 'C:\\Users\\10653\\AppData\\Local\\Temp\\pip-req-tracker-ca4m71x7'
Removed build tracker: 'C:\\Users\\10653\\AppData\\Local\\Temp\\pip-req-tracker-ca4m71x7'

**Comment by xpngzhng** [comment]
[WindowsRun.MD](https://github.com/Megvii-BaseDetection/YOLOX/files/6866366/WindowsRun.MD)

**Comment by flamebox** [comment]
是的，将open README.md这两句注释掉后，再将最下面的long_description=long_description粗暴改为long_description=“long_description”就可以了。。。

**Comment by TianQingX** [comment]
> 是的，将open README.md这两句注释掉后，再将最下面的long_description=long_description粗暴改为long_description=“long_description”就可以了。。。

是个方法，但我重装了VC之后，把cl文件添加回系统环境变量就可以安装yolo x了
只是又卡在安装apex 报了另外一个错误
![image](https://user-images.githubusercontent.com/40229906/126790845-ac32a068-1449-4564-b03e-a94c72f95c65.png)

**Comment by lihui669** [comment]
我整个环境终于搭好了

**Comment by TianQingX** [comment]
> 我整个环境终于搭好了

怎么装上去的 兄弟

**Comment by TianQingX** [comment]
> > 是的，将open README.md这两句注释掉后，再将最下面的long_description=long_description粗暴改为long_description=“long_description”就可以了。。。
> 
> 是个方法，但我重装了VC之后，把cl文件添加回系统环境变量就可以安装yolo x了
> 只是又卡在安装apex 报了另外一个错误
> ![image](https://user-images.githubusercontent.com/40229906/126790845-ac32a068-1449-4564-b03e-a94c72f95c65.png)

根据网页https://blog.csdn.net/weixin_38215769/article/details/106568368
要把第三行命令 
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
改成 
python setup.py install

**Comment by alistarhu** [comment]
> > pytorch vision must >=1.3
> > 您好，我把pytorch换成1.6   依然报相同的错误
> > ![image](https://user-images.githubusercontent.com/40649829/126650740-7897b3c4-7c39-4c7f-8ecb-afcd00765926.png)

I meet the same problem when i use python=3.6, because the default encoding is ASCII for python3.6.  I fixed it by changing encoding to utf-8 by `export PYTHONIOENCODING=utf-8`. Or you can choose python3.7 which default encoding is utf-8.

**Comment by qmcreeper** [comment]
我把README.md改成ANSI编码就跳过这个问题了

**Comment by wang-puwei** [comment]
setup.py里第51行改成，with open("README.md", "r", encoding = 'utf-8') as f: ，就好了

**Comment by YUANMU227** [comment]
> setup.py里第51行改成，with open("README.md", "r", encoding = 'utf-8') as f: ，就好了

没好呀，兄弟

**Comment by YUANMU227** [comment]
> 我把README.md改成ANSI编码就跳过这个问题了

咋改的兄弟

**Comment by YUANMU227** [comment]
> 我整个环境终于搭好了

咋搞的兄弟

**Comment by FateScript** [comment]
Encoding problem has been solved, Feel free to reopen.
